[project]
name = 'Licentra'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Licentra]
path = 'contracts/Licentra.clar'
clarity_version = 3
epoch = 3.1
[contracts.LicenseAnalytics]
path = 'contracts/LicenseAnalytics.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
